version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=africa
      - POSTGRES_PASSWORD=village_people
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      - '5555:5555'

  redis:
    image: "redis:7-alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  wait_for_redis:
    image: "redis:7-alpine"
    depends_on:
      - redis
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: sOmE_sEcUrE_pAsS
    ports:
      - 8081:8081

volumes:
  postgres: