version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=africa
      - POSTGRES_PASSWORD=village_people
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      - '5555:5555'
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  postgres: